[package]
name = "grip-rust"
version = "0.0.6-alpha"
authors = ["alik"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true
panic = "abort"

[features]
vendored = ["reqwest/default-tls-vendored"]
default = ["vendored"] # TODO: Conditional dynamic linking.

[dependencies]
bytes = "0.4.11"
crossbeam-channel = "0.3.8"
reqwest = { version = "0.9.9", features = ["trust-dns"] }
futures = "0.1.25"
derive_more = "0.14.0"
libc = "0.2.47"
tokio = "0.1.14"
derive_builder = "0.7.1"
error-chain = { version = "0.12.0", default-features = false }
log = "0.4.6"
rust-ini = "0.13.0"
clone_all = "0.1.1"
either = "1.5.0"
lazy_static = "1.2.0"
serde_json = "1.0.38"
float-cmp = "0.4.0"
itertools = "0.8.0"